[2023-12-26T13:20:11.276+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-18T00:00:00+00:00 [queued]>
[2023-12-26T13:20:11.280+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-18T00:00:00+00:00 [queued]>
[2023-12-26T13:20:11.281+0545] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-26T13:20:11.293+0545] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): fetch_and_store_metrics> on 2023-07-18 00:00:00+00:00
[2023-12-26T13:20:11.295+0545] {standard_task_runner.py:60} INFO - Started process 27367 to run task
[2023-12-26T13:20:11.297+0545] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'metrics_pipeline', 'fetch_and_store_metrics', 'scheduled__2023-07-18T00:00:00+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/taxi_metrics_dag.py', '--cfg-path', '/tmp/tmppnka4twa']
[2023-12-26T13:20:11.298+0545] {standard_task_runner.py:88} INFO - Job 202: Subtask fetch_and_store_metrics
[2023-12-26T13:20:11.323+0545] {task_command.py:423} INFO - Running <TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-18T00:00:00+00:00 [running]> on host Sarita-Thinkpad
[2023-12-26T13:20:11.376+0545] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='metrics_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_store_metrics' AIRFLOW_CTX_EXECUTION_DATE='2023-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-18T00:00:00+00:00'
[2023-12-26T13:20:11.394+0545] {python.py:201} INFO - Done. Returned value was: None
[2023-12-26T13:20:11.405+0545] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=metrics_pipeline, task_id=fetch_and_store_metrics, execution_date=20230718T000000, start_date=20231226T073511, end_date=20231226T073511
[2023-12-26T13:20:11.470+0545] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2023-12-26T13:20:11.497+0545] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-27T12:21:35.839+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-18T00:00:00+00:00 [queued]>
[2023-12-27T12:21:35.845+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-18T00:00:00+00:00 [queued]>
[2023-12-27T12:21:35.845+0545] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-27T12:21:35.857+0545] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): fetch_and_store_metrics> on 2023-07-18 00:00:00+00:00
[2023-12-27T12:21:35.859+0545] {standard_task_runner.py:60} INFO - Started process 13898 to run task
[2023-12-27T12:21:35.860+0545] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'metrics_pipeline', 'fetch_and_store_metrics', 'scheduled__2023-07-18T00:00:00+00:00', '--job-id', '408', '--raw', '--subdir', 'DAGS_FOLDER/taxi_metrics_dag.py', '--cfg-path', '/tmp/tmpjxclknlz']
[2023-12-27T12:21:35.861+0545] {standard_task_runner.py:88} INFO - Job 408: Subtask fetch_and_store_metrics
[2023-12-27T12:21:35.885+0545] {task_command.py:423} INFO - Running <TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-18T00:00:00+00:00 [running]> on host Sarita-Thinkpad
[2023-12-27T12:21:35.941+0545] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='metrics_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_store_metrics' AIRFLOW_CTX_EXECUTION_DATE='2023-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-18T00:00:00+00:00'
[2023-12-27T12:21:40.223+0545] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "//home/sarita/Documents/apache-airflow-project/dags/taxi_metrics_dag.py", line 58, in fetch_and_store_metrics
    clickhouse_data = get_clickhouse_data()
  File "//home/sarita/Documents/apache-airflow-project/dags/taxi_metrics_dag.py", line 33, in get_clickhouse_data
    result = clickhouse_conn.query(query)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/client.py", line 193, in query
    return self._query_with_context(query_context)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 209, in _query_with_context
    response = self._raw_request(body,
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 433, in _raw_request
    self._error_handler(response)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 357, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for https://github.demo.trial.altinity.cloud:8443 returned response code 400)
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 1290 (end of query) (line 23, col 11): ;

 FORMAT Native. . (SYNTAX_ERROR) (version 23.10.5.20 (official build))

[2023-12-27T12:21:40.239+0545] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=metrics_pipeline, task_id=fetch_and_store_metrics, execution_date=20230718T000000, start_date=20231227T063635, end_date=20231227T063640
[2023-12-27T12:21:40.254+0545] {standard_task_runner.py:107} ERROR - Failed to execute job 408 for task fetch_and_store_metrics (:HTTPDriver for https://github.demo.trial.altinity.cloud:8443 returned response code 400)
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 1290 (end of query) (line 23, col 11): ;

 FORMAT Native. . (SYNTAX_ERROR) (version 23.10.5.20 (official build))
; 13898)
[2023-12-27T12:21:40.290+0545] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-27T12:21:40.302+0545] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-27T12:22:59.205+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-18T00:00:00+00:00 [queued]>
[2023-12-27T12:22:59.211+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-18T00:00:00+00:00 [queued]>
[2023-12-27T12:22:59.211+0545] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-27T12:22:59.223+0545] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): fetch_and_store_metrics> on 2023-07-18 00:00:00+00:00
[2023-12-27T12:22:59.225+0545] {standard_task_runner.py:60} INFO - Started process 13939 to run task
[2023-12-27T12:22:59.227+0545] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'metrics_pipeline', 'fetch_and_store_metrics', 'scheduled__2023-07-18T00:00:00+00:00', '--job-id', '413', '--raw', '--subdir', 'DAGS_FOLDER/taxi_metrics_dag.py', '--cfg-path', '/tmp/tmp1c574j7f']
[2023-12-27T12:22:59.227+0545] {standard_task_runner.py:88} INFO - Job 413: Subtask fetch_and_store_metrics
[2023-12-27T12:22:59.252+0545] {task_command.py:423} INFO - Running <TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-18T00:00:00+00:00 [running]> on host Sarita-Thinkpad
[2023-12-27T12:22:59.307+0545] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='metrics_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_store_metrics' AIRFLOW_CTX_EXECUTION_DATE='2023-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-18T00:00:00+00:00'
[2023-12-27T12:23:03.302+0545] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "//home/sarita/Documents/apache-airflow-project/dags/taxi_metrics_dag.py", line 58, in fetch_and_store_metrics
    clickhouse_data = get_clickhouse_data()
  File "//home/sarita/Documents/apache-airflow-project/dags/taxi_metrics_dag.py", line 33, in get_clickhouse_data
    result = clickhouse_conn.query(query)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/client.py", line 193, in query
    return self._query_with_context(query_context)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 209, in _query_with_context
    response = self._raw_request(body,
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 433, in _raw_request
    self._error_handler(response)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 357, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for https://github.demo.trial.altinity.cloud:8443 returned response code 400)
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 1290 (end of query) (line 23, col 11): ;

 FORMAT Native. . (SYNTAX_ERROR) (version 23.10.5.20 (official build))

[2023-12-27T12:23:03.317+0545] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=metrics_pipeline, task_id=fetch_and_store_metrics, execution_date=20230718T000000, start_date=20231227T063759, end_date=20231227T063803
[2023-12-27T12:23:03.356+0545] {standard_task_runner.py:107} ERROR - Failed to execute job 413 for task fetch_and_store_metrics (:HTTPDriver for https://github.demo.trial.altinity.cloud:8443 returned response code 400)
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 1290 (end of query) (line 23, col 11): ;

 FORMAT Native. . (SYNTAX_ERROR) (version 23.10.5.20 (official build))
; 13939)
[2023-12-27T12:23:03.375+0545] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-27T12:23:03.388+0545] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
