[2023-12-26T13:20:20.490+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-12-26T13:20:20.494+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-12-26T13:20:20.494+0545] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-26T13:20:20.507+0545] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): fetch_and_store_metrics> on 2023-07-21 00:00:00+00:00
[2023-12-26T13:20:20.509+0545] {standard_task_runner.py:60} INFO - Started process 27389 to run task
[2023-12-26T13:20:20.511+0545] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'metrics_pipeline', 'fetch_and_store_metrics', 'scheduled__2023-07-21T00:00:00+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/taxi_metrics_dag.py', '--cfg-path', '/tmp/tmp9hh5d_fp']
[2023-12-26T13:20:20.512+0545] {standard_task_runner.py:88} INFO - Job 205: Subtask fetch_and_store_metrics
[2023-12-26T13:20:20.535+0545] {task_command.py:423} INFO - Running <TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-21T00:00:00+00:00 [running]> on host Sarita-Thinkpad
[2023-12-26T13:20:20.587+0545] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='metrics_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_store_metrics' AIRFLOW_CTX_EXECUTION_DATE='2023-07-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-21T00:00:00+00:00'
[2023-12-26T13:20:20.601+0545] {python.py:201} INFO - Done. Returned value was: None
[2023-12-26T13:20:20.605+0545] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=metrics_pipeline, task_id=fetch_and_store_metrics, execution_date=20230721T000000, start_date=20231226T073520, end_date=20231226T073520
[2023-12-26T13:20:20.643+0545] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2023-12-26T13:20:20.674+0545] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-27T12:21:59.589+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-12-27T12:21:59.593+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-12-27T12:21:59.593+0545] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-27T12:21:59.606+0545] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): fetch_and_store_metrics> on 2023-07-21 00:00:00+00:00
[2023-12-27T12:21:59.607+0545] {standard_task_runner.py:60} INFO - Started process 13917 to run task
[2023-12-27T12:21:59.609+0545] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'metrics_pipeline', 'fetch_and_store_metrics', 'scheduled__2023-07-21T00:00:00+00:00', '--job-id', '411', '--raw', '--subdir', 'DAGS_FOLDER/taxi_metrics_dag.py', '--cfg-path', '/tmp/tmpdmjrtyf7']
[2023-12-27T12:21:59.610+0545] {standard_task_runner.py:88} INFO - Job 411: Subtask fetch_and_store_metrics
[2023-12-27T12:21:59.634+0545] {task_command.py:423} INFO - Running <TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-21T00:00:00+00:00 [running]> on host Sarita-Thinkpad
[2023-12-27T12:21:59.679+0545] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='metrics_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_store_metrics' AIRFLOW_CTX_EXECUTION_DATE='2023-07-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-21T00:00:00+00:00'
[2023-12-27T12:22:05.706+0545] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "//home/sarita/Documents/apache-airflow-project/dags/taxi_metrics_dag.py", line 58, in fetch_and_store_metrics
    clickhouse_data = get_clickhouse_data()
  File "//home/sarita/Documents/apache-airflow-project/dags/taxi_metrics_dag.py", line 33, in get_clickhouse_data
    result = clickhouse_conn.query(query)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/client.py", line 193, in query
    return self._query_with_context(query_context)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 209, in _query_with_context
    response = self._raw_request(body,
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 433, in _raw_request
    self._error_handler(response)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 357, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for https://github.demo.trial.altinity.cloud:8443 returned response code 400)
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 1290 (end of query) (line 23, col 11): ;

 FORMAT Native. . (SYNTAX_ERROR) (version 23.10.5.20 (official build))

[2023-12-27T12:22:05.723+0545] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=metrics_pipeline, task_id=fetch_and_store_metrics, execution_date=20230721T000000, start_date=20231227T063659, end_date=20231227T063705
[2023-12-27T12:22:05.743+0545] {standard_task_runner.py:107} ERROR - Failed to execute job 411 for task fetch_and_store_metrics (:HTTPDriver for https://github.demo.trial.altinity.cloud:8443 returned response code 400)
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 1290 (end of query) (line 23, col 11): ;

 FORMAT Native. . (SYNTAX_ERROR) (version 23.10.5.20 (official build))
; 13917)
[2023-12-27T12:23:28.100+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-12-27T12:23:28.106+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-12-27T12:23:28.106+0545] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-27T12:23:28.118+0545] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): fetch_and_store_metrics> on 2023-07-21 00:00:00+00:00
[2023-12-27T12:23:28.120+0545] {standard_task_runner.py:60} INFO - Started process 13955 to run task
[2023-12-27T12:23:28.123+0545] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'metrics_pipeline', 'fetch_and_store_metrics', 'scheduled__2023-07-21T00:00:00+00:00', '--job-id', '416', '--raw', '--subdir', 'DAGS_FOLDER/taxi_metrics_dag.py', '--cfg-path', '/tmp/tmp5ivtbtp_']
[2023-12-27T12:23:28.123+0545] {standard_task_runner.py:88} INFO - Job 416: Subtask fetch_and_store_metrics
[2023-12-27T12:23:28.149+0545] {task_command.py:423} INFO - Running <TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-21T00:00:00+00:00 [running]> on host Sarita-Thinkpad
[2023-12-27T12:23:28.194+0545] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='metrics_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_store_metrics' AIRFLOW_CTX_EXECUTION_DATE='2023-07-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-21T00:00:00+00:00'
[2023-12-27T12:23:33.469+0545] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "//home/sarita/Documents/apache-airflow-project/dags/taxi_metrics_dag.py", line 58, in fetch_and_store_metrics
    clickhouse_data = get_clickhouse_data()
  File "//home/sarita/Documents/apache-airflow-project/dags/taxi_metrics_dag.py", line 33, in get_clickhouse_data
    result = clickhouse_conn.query(query)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/client.py", line 193, in query
    return self._query_with_context(query_context)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 209, in _query_with_context
    response = self._raw_request(body,
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 433, in _raw_request
    self._error_handler(response)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 357, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for https://github.demo.trial.altinity.cloud:8443 returned response code 400)
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 1290 (end of query) (line 23, col 11): ;

 FORMAT Native. . (SYNTAX_ERROR) (version 23.10.5.20 (official build))

[2023-12-27T12:23:33.476+0545] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=metrics_pipeline, task_id=fetch_and_store_metrics, execution_date=20230721T000000, start_date=20231227T063828, end_date=20231227T063833
[2023-12-27T12:23:33.491+0545] {standard_task_runner.py:107} ERROR - Failed to execute job 416 for task fetch_and_store_metrics (:HTTPDriver for https://github.demo.trial.altinity.cloud:8443 returned response code 400)
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 1290 (end of query) (line 23, col 11): ;

 FORMAT Native. . (SYNTAX_ERROR) (version 23.10.5.20 (official build))
; 13955)
[2023-12-27T12:23:33.541+0545] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-27T12:23:33.548+0545] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
